name: job_gen_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.5
  get_it: ^7.7.0
  flutter_secure_storage: ^9.2.2
  formz: ^0.7.0
  cupertino_icons: ^1.0.8
  country_state_city_pro: ^0.0.6
  country_picker: ^2.0.0 
  
  # Functional programming and error handling
  dartz: ^0.10.1
  
  # Network and connectivity
  connectivity_plus: ^6.1.4
  http: ^1.2.0

  # Local storage
  shared_preferences: ^2.2.2
  bloc: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/
    